enum ErrorCode {
  OPEN_QUALITY_CHECKER_ADMIN_TOKEN_REQUIRED,
  WORKSPACE_MAPPING_NOT_FOUND,
  OPEN_QUALITY_CHECKER_PROJECT_IDS_REQUIRED,
  OPEN_QUALITY_CHECKER_ERROR,
  INTERNAL_SERVER_ERROR,
  REPOSITORY_MAPPING_NOT_FOUND,
  BITBUCKET_REPOSITORY_ID_REQUIRED,
  BITBUCKET_PULL_REQUEST_ID_REQUIRED,
  BITBUCKET_API_ERROR,
}

export default ErrorCode;
