version: '3.5'

services:
  check:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: oqcp-bitbucket-frontend-checker
    volumes:
      - ./test:/usr/src/app/test
    command: yarn test-ci
    environment:
      - JEST_REPORT_FILE=./test/jest-report.json
